apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-pro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RomalB22/gitops
    targetRevision: HEAD
    path: environments/pro
  destination:
    server: https://kubernetes.default.svc
    namespace: pro
  syncPolicy:
    automated: {}
